"""
Compliance scan for outbound research reports.

Two responsibilities:
  1. Flag prohibited terms (absolute language that misrepresents risk) and
     replace them with neutral alternatives. Sourced from equity-research
     repo's config.example.json `compliance.prohibited_terms`.
  2. Ensure the mandatory educational / non-advice disclaimer is present.

Usage:
    cleaned, violations = compliance_check(report_md)
    # `violations` is a list of dicts; each flagged instance logs a warning.
    # `cleaned` has replacements applied and the disclaimer appended if missing.
"""

from __future__ import annotations

import re

import structlog

logger = structlog.get_logger()


# Absolute-language terms that misrepresent investment risk.
# Order matters: more specific multi-word phrases come before single words
# so they replace cleanly before the single-word regex fires.
PROHIBITED_TERMS: dict[str, str] = {
    "sure thing": "high-conviction idea",
    "risk-free": "lower-risk",
    "risk free": "lower-risk",
    "guaranteed": "potentially",
    "guarantee": "estimate",
    "always profitable": "historically profitable",
    "can't lose": "has historically performed well",
    "cannot lose": "has historically performed well",
    "no downside": "limited downside",
}

DISCLAIMER_MARKER = "**Disclaimer:**"

DISCLAIMER_TEXT = (
    "\n\n---\n\n"
    "**Disclaimer:** This report is generated by an automated research pipeline "
    "for educational and informational purposes only. It does not constitute "
    "investment advice, an offer to buy or sell any security, or a recommendation. "
    "All statistics are derived from historical data; past performance is not "
    "indicative of future results. Consult a licensed financial advisor before "
    "making investment decisions.\n"
)


def compliance_check(report_md: str) -> tuple[str, list[dict]]:
    """
    Scan a report for prohibited terms, replace them, and ensure disclaimer.

    Args:
        report_md: Full markdown report string.

    Returns:
        Tuple of (cleaned_md, violations). `violations` is a list of dicts
        with term, replacement, and a snippet of surrounding context.
    """
    if not report_md:
        return report_md, []

    violations: list[dict] = []
    cleaned = report_md

    for term, replacement in PROHIBITED_TERMS.items():
        pattern = re.compile(r"\b" + re.escape(term) + r"\b", re.IGNORECASE)
        for match in pattern.finditer(cleaned):
            snippet = _context_snippet(cleaned, match.start(), match.end())
            violations.append(
                {
                    "term": term,
                    "replacement": replacement,
                    "context": snippet,
                    "position": match.start(),
                }
            )
        cleaned = pattern.sub(replacement, cleaned)

    cleaned = ensure_disclaimer(cleaned)

    if violations:
        logger.warning(
            "compliance.violations_found",
            count=len(violations),
            terms=sorted({v["term"] for v in violations}),
        )

    return cleaned, violations


def ensure_disclaimer(report_md: str) -> str:
    """Append the mandatory disclaimer if absent."""
    if DISCLAIMER_MARKER in report_md:
        return report_md
    return report_md.rstrip() + DISCLAIMER_TEXT


def _context_snippet(text: str, start: int, end: int, radius: int = 40) -> str:
    """Return a short ±40-char window around a match, with ellipses."""
    left = max(0, start - radius)
    right = min(len(text), end + radius)
    snippet = text[left:right].replace("\n", " ")
    prefix = "…" if left > 0 else ""
    suffix = "…" if right < len(text) else ""
    return f"{prefix}{snippet}{suffix}"
